In [1]:
import pandas as pd
import numpy as np

In [2]:
ar = [[1,2,3,5], [8,3,6,7]]

In [3]:
ar

[[1, 2, 3, 5], [8, 3, 6, 7]]

In [4]:
ar = np.array(ar)

In [5]:
ar

array([[1, 2, 3, 5],
       [8, 3, 6, 7]])

# How to reshape a numpy array

In [6]:
ar.shape

(2, 4)

In [7]:
ar1 = np.reshape(ar, (4,2))

In [8]:
ar1

array([[1, 2],
       [3, 5],
       [8, 3],
       [6, 7]])

In [9]:
ar2 = np.reshape(ar, (4, -1))

In [10]:
ar2

array([[1, 2],
       [3, 5],
       [8, 3],
       [6, 7]])

In [11]:
ar3 = np.reshape(ar, (2,2,2))

In [12]:
ar3

array([[[1, 2],
        [3, 5]],

       [[8, 3],
        [6, 7]]])

In [13]:
ar3.shape

(2, 2, 2)

# How to find Element-wise maximum of array elements.

In [14]:
import numpy as np

In [15]:
li1 = [3,0,8,4]
li2 = [2,4,5,7]

In [16]:
max_li = np.fmax(li1, li2)

In [17]:
print(max_li)

[3 4 8 7]


# How to find Element-wise minimum of array elements.

In [18]:
min_li = np.fmin(li1, li2)

In [19]:
print(min_li)

[2 0 5 4]


# How to Return the maximum of an array or maximum along an axis.

In [20]:
grid = [[3,0,8,4],[2,4,5,7],[9,2,6,3],[0,3,1,0]]

In [21]:
print(np.amax(grid, axis = 0))

[9 4 8 7]


In [22]:
print(np.max(grid, axis = 1))

[8 7 9 3]


# How to Return the minimum of an array or maximum along an axis.

In [23]:
print(np.amin(grid, axis = 0))

[0 0 1 0]


In [24]:
print(np.amin(grid, axis = 1))

[0 2 2 0]


# How to return Sum of array elements over a given axis

In [25]:
grid = [[3,0,8,4],[2,4,5,7],[9,2,6,3],[0,3,1,0]]

In [26]:
print(np.sum(grid, axis = 0))

[14  9 20 14]


In [27]:
print(np.sum(grid, axis = 1))

[15 18 20  4]


# How to calculate a prefix sum

In [28]:
import numpy as np

In [29]:
arr1 = [1,2,3,4]
pre_sum = np.cumsum(arr1)
print(pre_sum)

[ 1  3  6 10]


# How to create a pandas series of random numbers

In [2]:
data = pd.Series(np.random.randn(1000))

In [3]:
data

0      0.715220
1      0.274528
2     -0.346799
3     -0.660199
4      1.191697
         ...   
995    0.151728
996   -0.742289
997    0.700734
998    0.202443
999    0.025747
Length: 1000, dtype: float64