# sliding window

https://itnext.io/sliding-window-algorithm-technique-6001d5fbe8b3

https://www.baeldung.com/cs/sliding-window-algorithm

In [1]:
def sliding_window(sequence, n):
    for i in range(len(sequence) - n + 1):
        yield sequence[i:i + n]
        
#test
for window in sliding_window([1, 2, 3, 4, 5, 6], 3):
    print(window)

[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]


# Variable-size sliding window

In [2]:
from collections import deque

def sliding_window(data, window_size):
    window = deque()
    for i, element in enumerate(data):
        window.append(element)
        if i >= window_size:
            window.popleft()
        if i >= window_size - 1:
            yield list(window)

# Example usage
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for window in sliding_window(data, 3):
    print(window)

[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]
[5, 6, 7]
[6, 7, 8]
[7, 8, 9]
[8, 9, 10]


# yield and return

In [11]:
def count_up_to(max):
    count = 1
    while count <= max:
        yield count
        count += 1

def count_up_to_return(max):
    count = 1
    while count <= max:
        return count
        #count += 1

# Example usage
for number in count_up_to(5):
    print(number)

print(count_up_to(5),"\n")

print(count_up_to_return(5))

1
2
3
4
5
<generator object count_up_to at 0x7fc41c76a570> 

1


# count the frequency of elements in an window of an array using counter

In [4]:
from collections import Counter

def sliding_window_count(data, window_size):
    counter = Counter()
    for i, element in enumerate(data):
        counter[element] += 1
        if i >= window_size:
            counter[data[i - window_size]] -= 1
        if i >= window_size - 1:
            yield counter

# Example usage
data = [1, 2, 3, 2, 1, 2, 3, 1, 2, 3]
for count in sliding_window_count(data, 3):
    print(count)


Counter({1: 1, 2: 1, 3: 1})
Counter({2: 2, 3: 1, 1: 0})
Counter({1: 1, 2: 1, 3: 1})
Counter({2: 2, 1: 1, 3: 0})
Counter({1: 1, 2: 1, 3: 1})
Counter({1: 1, 2: 1, 3: 1})
Counter({1: 1, 2: 1, 3: 1})
Counter({1: 1, 2: 1, 3: 1})


# lambda function

In [5]:
multiply = lambda x, y : x*y
print(multiply(3,5))

15


In [6]:
power =lambda x,y: x**y
print(power(2,3))

8


# map function

In [7]:
def attendance(percent):
    if percent > 80:
        return "pass"
    elif percent > 40:
        return "justpass"
    else:
        return "fail"


In [8]:
att = [34, 45, 76, 98, 78]
for percen in att:
    print(attendance(percen))

fail
justpass
justpass
pass
justpass


In [9]:
li = list(map(attendance, att))
print(li)

['fail', 'justpass', 'justpass', 'pass', 'justpass']


# map function with lambda function

In [10]:
li1 = [34, 23, 56, 78, 42, 62, 46]
li2 = [35, 78, 9, 35, 467, 67, 232]
diff = list(map(lambda x, y: x-y, li1, li2))
avg = list(map(lambda x, y: (x+y)//2, li1, li2))
print(avg)
print(diff)

[34, 50, 32, 56, 254, 64, 139]
[-1, -55, 47, 43, -425, -5, -186]


In [11]:
fruits = ["apple","mango", "grape", "pineapple"]
capital = list(map(lambda x:x.upper(), fruits))
print(capital)

['APPLE', 'MANGO', 'GRAPE', 'PINEAPPLE']


# filter function with lambda fucntion

In [12]:
li = [23, 64, 45, 78, 97, 98]
even = list(filter(lambda x: x%2 == 0, li))
print(even)

[64, 78, 98]


In [13]:
vowel = ["a","e","i", "o", "u"]
letters = ["s","e", "i", "i", "w", "w","p"]
fil_vowel = list(filter(lambda x: x in vowel, letters))
print(fil_vowel)

['e', 'i', 'i']


In [14]:
countries = ["India", "US", "UK", "France", "China", "Germany", "UAE"]
coun = list(filter(lambda x: len(x) > 3, countries))
print(coun)

['India', 'France', 'China', 'Germany']


# sorting with lambda function

In [15]:
attendance1 = [35,39,32,37,30,33]
print(sorted(attendance1))

[30, 32, 33, 35, 37, 39]


In [16]:
print(sorted(attendance1, reverse=True))

[39, 37, 35, 33, 32, 30]


In [17]:
class_attendance = [('9A', 35),('9B', 37), ('9C',30), ('9D',32),('9E',34)]
sor_att = sorted(class_attendance, key = lambda x: x[1])
print(sor_att)

[('9C', 30), ('9D', 32), ('9E', 34), ('9A', 35), ('9B', 37)]


# lambda and map function with dictionaries

In [18]:
sales = [
            {'country': 'India', 'sale' : 150},
            {'country': 'Chine', 'sale' : 200},
            {'country': 'US', 'sale' : 300},
            {'country': 'UK', 'sale' : 400},
            {'country': 'Germany', 'sale' : 500}
        ]
sales

[{'country': 'India', 'sale': 150},
 {'country': 'Chine', 'sale': 200},
 {'country': 'US', 'sale': 300},
 {'country': 'UK', 'sale': 400},
 {'country': 'Germany', 'sale': 500}]

In [19]:
country = list(map(lambda x: x["country"], sales))
print(country)

['India', 'Chine', 'US', 'UK', 'Germany']


In [20]:
sales = list(map(lambda x: x["sale"], sales))
print(sales)

[150, 200, 300, 400, 500]


india_sale = list(filter(lambda x: x["country"] == "India", sales))
print(india_sale)

high_sale = list(filter(lambda x: x["sale"] > 250, sales))
print(high_sale)

# bisect library in python

In [21]:
from bisect import bisect_left, bisect, bisect_right,insort_left, insort, insort_right

In [22]:
numbers = [1, 2, 4, 4, 5, 7, 8]

In [23]:
print(bisect(numbers, 1))

1


In [24]:
print(bisect_left(numbers, 4))

2


In [25]:
insort(numbers, 6)
print(numbers)

[1, 2, 4, 4, 5, 6, 7, 8]


# prefix sum using itertools.accumulate

In [26]:
li1 = [1, 3, 4, 7]

In [27]:
from itertools import accumulate
cum_sum = list(accumulate(li1))
print(cum_sum)

[1, 4, 8, 15]


In [28]:
print(8)

8


# How to transpose rows into columns in a grid matrix

In [29]:
import numpy as np

In [30]:
grid = np.array([[3,0,8,4],[2,4,5,7],[9,2,6,3],[0,3,1,0]])

In [31]:
print(grid)

[[3 0 8 4]
 [2 4 5 7]
 [9 2 6 3]
 [0 3 1 0]]


In [32]:
grid_t = np.array(list((zip(*grid))))

In [33]:
print(grid_t)

[[3 2 9 0]
 [0 4 2 3]
 [8 5 6 1]
 [4 7 3 0]]


# How to create a defaultdict of type list

In [34]:
from collections import defaultdict

In [35]:
map_dic = defaultdict(list)

In [36]:
print(map_dic)

defaultdict(<class 'list'>, {})


In [37]:
print(map_dic["d"])

[]


In [38]:
print(map_dic["3"])

[]


In [39]:
print(6)

6


# How to find gcd using math module

In [40]:
from math import gcd

In [41]:
ans = gcd(12, 16)
print(ans)

4


# How to find gcd using Euclidean Algorithm

In [42]:
def gcd_c(x, y):
    while y:
        x, y = y, x % y
    return x

In [43]:
print(gcd_c(12, 16))

4


In [44]:
print(4%2)

0


In [45]:
print(2%4)

2


In [46]:
ar = {3,5,6}

In [47]:
print(type(ar))

<class 'set'>


In [48]:
d = {v: k for k, v in enumerate("abcde", start = 1)}

In [49]:
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [50]:
d["a"]

1

In [51]:
d.get("a")

1

In [52]:
li1 = [-1, 1, 2 , -2, 3, 8, -3, -2, 10, -7, -5]

In [53]:
li1

[-1, 1, 2, -2, 3, 8, -3, -2, 10, -7, -5]

In [54]:
print(sorted(li1, key = abs))

[-1, 1, 2, -2, -2, 3, -3, -5, -7, 8, 10]


# HOw to sort an array based on a key function like absolute and length

In [55]:
numbers = [-3, -1, 4, 1, -5, 9, -2, 6, 5, -3, 5]

In [56]:
print(sorted(numbers, key = abs))

[-1, 1, -2, -3, -3, 4, -5, 5, 5, 6, 9]


# How to convert a decimal number to binary

In [57]:
num = 45
print(bin(45))

0b101101


In [58]:
print(bin(num))

0b101101


# How to convert binary to decimal number

In [59]:
print(int('0b101101', 2))

45


# How to convert decimal to octal

In [60]:
print(oct(45))

0o55


# How to convert octal to decimal

In [61]:
print(int('55', 8))

45


# How to convert decimal to hexadecimal

In [62]:
print(hex(45))

0x2d


# How to convert hexadecimal to decimal

In [63]:
print(int("2d", 16))

45


In [64]:
print(10 ^ 7)

13


In [65]:
print(int(True))

1


In [66]:
print(int(False))

0


In [67]:
print(5 & 1)

1


In [68]:
print(5 & 0)

0


In [69]:
print(4 & 1)

0


In [70]:
print(4 & 0)

0


In [71]:
print(bool(5))

True


In [72]:
print(bool(0))

False


In [73]:
odd = 5

In [74]:
print(odd & 1)

1


In [75]:
even = 8

In [76]:
print(even & 1)

0


# How to check if a number is even or odd using bitwise and operator
## comparing least significant bit(LSB) of the number with 1
### 1 & 1 = 1
### 0 & 1 = 0

### in even LSB is 0
### in odd LSB is 1

In [77]:
print(14 & 1)

0


In [78]:
even = 8
odd = 7


In [79]:
print(even & 1)

0


In [80]:
print(odd & 1)

1


# How to check if 2 integers have opposite sign or not using XOR operation
## comparing both of their most significant bit with each other
### for similar sign integers XOR will set MSB of the output to 0
### for opposite sign integers XOR will set MSB of the output to 1
### for positive number the MSB is 0
### for negative number the MSB is 1

In [81]:
num = 4
neg = -8
pos = 8

In [82]:
print(num ^ pos)

12


In [83]:
print(num ^ neg)

-4


In [84]:
print(bin(8))

0b1000


In [85]:
print(bin(-8))

-0b1000


In [86]:
print(4 ^ -8)

-4


In [87]:
print(4 ^ 8)

12


In [88]:
print(-4 ^ 8)

-12


In [89]:
print(-4 ^ -8)

4


### When the XOR operator is applied to a number with itself, it returns 0. Therefore, when the same number occurs twice in the list, its XOR operation will result in 0. 

In [1]:
nums = [2,4,5,4,3,5,2]
ans = 0
for num in nums:
     ans ^= num
print(ans)

3


# The bitwise complement operator in Python is ~. It inverts all the bits of an integer, effectively flipping 1s to 0s and 0s to 1s.

In [90]:
x = 5

In [91]:
print(x)

5


In [92]:
print(~5)

-6


# The negation operator in programming is the symbol - used to negate the value of a numeric expression, i.e., it changes the sign of the expression from positive to negative or vice versa. For example, -5 is the negation of 5, and -(-5) is the negation of -5, which is equal to 5.

In [93]:
x = 5
y = -x

In [94]:
print(x)
print(y)

5
-5


# How to add 1 to an integer using bit manipulation
## The expression -~x adds 1 to an integer x by leveraging the properties of the bitwise complement operator ~ and the negation operator -.

In [95]:
a = 5
b = -~a
print(b)

6


In [96]:
p = 5
q = ~p
r = -q

In [97]:
print(p)
print(q)
print(r)

5
-6
6


# How to subtract 1 from an integer using bit manipulation

In [98]:
i = 5
j = ~-i
print(j)

4


In [99]:
x = 5
y = -x
z = ~y

In [100]:
print(x)
print(y)
print(z)

5
-5
4


https://medium.com/techie-delight/bit-manipulation-interview-questions-and-practice-problems-27c0e71412e7

# How to swap two numbers using bit manipulation in Python by using the XOR operator (^) and without using a temporary variable.

In [101]:
a = 5
b = 6
print(a, b)

5 6


In [102]:
a = a ^ b
print(a)

3


In [103]:
b = a ^ b
print(b)

5


In [104]:
a = a ^ b
print(a)

6


In [105]:
print(a, b)

6 5


In [106]:
7

7

In [107]:
x = 4 ^ 7

In [108]:
print(x)

3


# Commutativity: XOR is commutative, which means that the order of the operands does not affect the result. For example, "a XOR b = b XOR a".

# Associativity: XOR is associative, which means that the operation can be grouped in different ways without affecting the result. For example, "(a XOR b) XOR c = a XOR (b XOR c)".

In [109]:
x = 3
y = 4
z = 7
print(y ^ z)

3


In [110]:
print(z ^ y)

3


In [111]:
print(y ^ x)

7


In [112]:
print(z ^ x)

4


In [113]:
print(bin(4))

0b100


In [114]:
x = 4
print(x.bit_length())

3


In [115]:
print(x)

4


In [116]:
print(x.bit_count())

1


In [117]:
print(16)

16


In [118]:
print(bin(20))

0b10100


In [119]:
print(int(5).bit_count())

2


In [120]:
print(bin(5))

0b101


In [121]:
print(int(5).bit_length())

3


# when we divide a even number by 2 its LSD will shift to 1 position left
## here right shift operator will act like we are dividing the number by 2
# when we subtract a odd number by 1 its LSD will be replaced with its complement i.e " 0 "

In [122]:
even = 14
print(bin(even))

0b1110


In [123]:
odd = even // 2
print(odd)
print(bin(odd))

7
0b111


In [124]:
even1 = odd -1
print(even1)
print(bin(even1))

6
0b110


In [125]:
print(bin(18))
print(bin(18//2))

0b10010
0b1001


In [126]:
print(int("1001", 2))

9


In [127]:
print(bin(17))
print(bin(17//2))

0b10001
0b1000


In [128]:
print(bin(17 >> 1))

0b1000


# To convert the least significant bit (LSB) of a binary representation to its opposite (i.e., from 0 to 1 or from 1 to 0), you can use the bitwise XOR operator (^) in combination with the value 1 (represented in binary as 0b0001). The XOR operation between any bit and 1 will flip the value of the bit.

In [129]:
x = 10
y = x ^ 1
print(bin(10))
print(y)
print(bin(y))

0b1010
11
0b1011


In [130]:
print(bin(14))

0b1110


# The "n & (n-1)" technique is a common operation in bit manipulation that is used to clear the "1" from the least significant bit. The idea is to subtract 1 from the number and perform a bitwise AND operation between the original number and the result.

In [131]:
def count_set_bits(n):
    steps_count = 0
    while n:
        
        print()
        print(n , bin(n))
        print(n -1, bin(n -1))
        
        n &= n-1
        
        print(n)
        
        steps_count += 1
        
    return steps_count


print(count_set_bits(13))


13 0b1101
12 0b1100
12

12 0b1100
11 0b1011
8

8 0b1000
7 0b111
0
3


In [132]:
x = 11
print(x)
print(bin(x))

11
0b1011


In [133]:
y = x - 1
print(y)
print(bin(y))
print(bin(x & y))

10
0b1010
0b1010


In [134]:
z = y -1
print(z)
print(bin(z))
print(bin(z & y))

9
0b1001
0b1000


In [135]:
9

9

# xor operation lets us find the total number of differnt bits between 2 numbers

In [136]:
x = 10
y = 7
print(bin(10))
print(bin(7))
z = x ^ y
print(z)
print(bin(z))

0b1010
0b111
13
0b1101


In [137]:
a = 3
b = 4
print(bin(3))
print(bin(4))
c = a ^ b
print(c)
print(bin(c))

0b11
0b100
7
0b111


# to count the number of set bits in a number

In [138]:
def count_set_bits(n):
    count = 0
    while n:
        n &= n-1
        count += 1
    return count

In [139]:
print(count_set_bits(13))
print(bin(13))

3
0b1101


In [140]:
print(bin(3))

0b11


# How The expression i & 1 and i % 2 can give the same result?
#### because both expressions evaluate to the least significant bit of an integer value i.
#### The expression i & 1 uses bitwise AND operation to isolate the least significant bit. When i is even, the least significant bit is 0, and when i is odd, the least significant bit is 1.
#### The expression i % 2 calculates the remainder of i divided by 2. Since any odd number divided by 2 gives a remainder of 1 and any even number divided by 2 gives a remainder of 0, this expression also evaluates to the least significant bit of i.

In [141]:
even = 2
odd = 3
print(even & 1)
print(odd & 1)

print(even % 2)
print(odd % 2)

0
1
0
1


# when we bit shift to left the number is multiplied by 2 and when we bit shift to right the number is divided by 2

In [142]:
print(bin(7))
print(7 << 1, bin(7 << 1))
print(7 >> 1, bin(7 >> 1))

0b111
14 0b1110
3 0b11


# How to convert a binary array to decimal using left shift operator

In [8]:
def binary_dec(arr):
    ans = 0
    while arr:
        ans = ans << 1 | arr.pop(0)
    return ans

In [9]:
arr9 = [1,0,1]
print(arr9)
print(binary_dec(arr9))

[1, 0, 1]
5


In [13]:
print(bin(57))
print(int("111101", 2))

0b111001
61


In [4]:
print(4 | 1)

5


In [143]:
print(14 << 1)

28


In [144]:
print(28 << 1)

56


In [145]:
print(29 >> 1)

14


In [146]:
print(29 >> 2)

7


# How to convert number to binary using python f-string formatting

In [147]:
num = 10
print(bin(num))
print(f'{num:b}')
print(f'{num:032b}')
print(f'{num:08b}')

0b1010
1010
00000000000000000000000000001010
00001010


# How to perform bit intersection between 2 numbers

In [148]:
num3 = 0b00110101   # 53 in decimal
num4 = 0b11001100   # 204 in decimal

In [149]:
# perform bit intersection using the bitwise AND operator
result = num3 & num4 

In [150]:
print(num)
print(result)

10
4


# How to apply bitwise or operation in 2 numbers 

In [151]:
a = 10
b = 11
c = a | b
print(c)
print(bin(a))
print(bin(b))
print(bin(c))

11
0b1010
0b1011
0b1011


In [152]:
print(bin(10))

0b1010


In [153]:
print(int("1010", 2))

10


# How to use reduce functions from functools to reduce a iterable to a single value

In [154]:
from functools import reduce

iterable_list = [2, 5, 5, 8, 7, 3]
def sum_list(a, b):
    return a + b

final_value = reduce(sum_list, iterable_list)

print(final_value)

30


# How to find the bitwise or value of a list using builtin ior function

In [155]:
from functools import reduce
from operator import ior

li3 = [3,7,2,8,9]

or_ope = reduce(ior, li3)

print(or_ope)

15


In [156]:
print(np.cumsum(li3))

[ 3 10 12 20 29]


In [157]:
for i in range(1, len(li3)):
    li3[i] = li3[i-1] + li3[i]

In [158]:
print(li3)

[3, 10, 12, 20, 29]


In [159]:
li4 = [2,4,6,7,8,3,6,2,7,9]
print(list(set(li4)))

[2, 3, 4, 6, 7, 8, 9]


In [160]:
num5 = 13
li5 = []
while num5 != 0:
    li5.append(str(num5 % 10))
    num5 = num5 // 10

In [161]:
print(int("".join(li5)))

31


In [162]:
m = 3
n = 3
k = 1

for i in range(m):
    for j in range(n):
        r_start = (i-k) if (i-k) in range(m) else 0
        r_end = (i+k) if (i+k) in range(m) else (m+1)
        c_start = (j-k) if (j-k) in range(n) else 0
        c_end = (j+k) if (j+k) in range(n) else (n+1)     
        print(r_start, r_end, c_start, c_end)


0 1 0 1
0 1 0 2
0 1 1 4
0 2 0 1
0 2 0 2
0 2 1 4
1 4 0 1
1 4 0 2
1 4 1 4


# How to implement monotonically decreasing stack

In [163]:
def make(A):
        n = len(A)
        result = [None] * n
        stack = []  
        for i in A:
            while stack and i > stack[-1]:
                result[stack.pop()] = i
            stack.append(i)
        return result

arr1= [0, 2, 1, 3, 4]
print(make(arr1))

[2, 3, 3, 4, None]


In [164]:
s = "aba"
temp = ""
list = []
for let in s:
    if let not in temp:
        temp += let
    else:
        list.append(temp)
        temp = ""
print(list)

['ab']


In [165]:
from itertools import accumulate

arr2 = [1,2,4,6,7]

result1 = accumulate(arr2)

for x in result1:
    print(x)

1
3
7
13
20


In [166]:
result2 = accumulate(arr2, multiply)

for y in result2:
    print(y)

1
2
8
48
336


# How to sort an array based on multiple keys using sorted & lambda function

In [167]:
nums1 = [1,1,2,2,2,3]
from collections import Counter
def frequencySort(nums):
    count = Counter(nums)
    return sorted(nums, key=lambda x: (count[x], -x))

# count[x] as the primary key
# -x as the secondary key

print(frequencySort(nums1))

[3, 1, 1, 2, 2, 2]


# How to find permutations and combinations using python

In [168]:
from itertools import permutations, combinations

elements = ["a", "b", "c"]

# Permutations P(n, k) = n! / (n - k)!

In [169]:
per = permutations(elements)

for perm in per:
    print(perm)


('a', 'b', 'c')
('a', 'c', 'b')
('b', 'a', 'c')
('b', 'c', 'a')
('c', 'a', 'b')
('c', 'b', 'a')


# Circular Permutations =  (n-1)!

# Combinations C(n, k) = n! / (k! * (n - k)!)

In [170]:
from itertools import combinations

arr3 = combinations(elements, 2)
for comb in arr3:
    print(comb)

('a', 'b')
('a', 'c')
('b', 'c')


# How to find out the number of combination k items from total n items

In [171]:
from math import comb
print(comb(3,2))

3


In [172]:
print(6 % 10)

6


In [173]:
print(16 % 10)

6


In [174]:
print(10 % 10)

0


In [175]:
from itertools import chain
list1 = [1,3,5,6]
list2 = [3,6,7,8]
list3 = [6,3,7,5]

list4 = list1 + list2 + list3
list5 = chain(list1, list2, list3)

print(list4)
for item in list5:
    print(item)

[1, 3, 5, 6, 3, 6, 7, 8, 6, 3, 7, 5]
1
3
5
6
3
6
7
8
6
3
7
5


# How to create a pascal triangle with only ones 

In [177]:
ans = []
size = 5

for i in range(1, size+1):
    li = [1] * i
    ans.append(li)
print(ans)


[[1], [1, 1], [1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1]]


In [178]:
size = 5
ans1 = [[1]*i for i in range(1, size+1)]
print(ans1)

[[1], [1, 1], [1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1]]


In [5]:
x = 1
y = 2


In [4]:
li = ["R", "B","G", "R"]
print(li)

['R', 'B', 'G', 'R']


In [6]:
print(set(li))

{'B', 'R', 'G'}


In [2]:
print(ord("z"))

122


# How to merge 2 dictionaries

In [1]:
dic1= {"a":"1", "b":"2"}
dic2 = {"c":"3", "d":"4"}

In [2]:
dic1.update(dic2)

In [3]:
print(dic1)

{'a': '1', 'b': '2', 'c': '3', 'd': '4'}


# How to use setdefault function in dictionaries

In [1]:
dic3 = {"a":1, "b":2}
print(dic3)

{'a': 1, 'b': 2}


In [3]:
dic3.setdefault("c",3)

3

In [5]:
dic3["c"] = 4

In [6]:
print(dic3)

{'a': 1, 'b': 2, 'c': 4}


# How to use elements method from the counter module

In [12]:
from collections import Counter
arr4 = [1,4,6,2,5,4,6,2,2,1,4,6]
count = Counter(arr4)
print(arr4)
print(count)

[1, 4, 6, 2, 5, 4, 6, 2, 2, 1, 4, 6]
Counter({4: 3, 6: 3, 2: 3, 1: 2, 5: 1})


In [15]:
k = max(count.values())
li6 = list(sorted(count.elements()))
li7 = list(count.elements())
print(k)
print(li6)
print(li7)

3
[1, 1, 2, 2, 2, 4, 4, 4, 5, 6, 6, 6]
[1, 1, 4, 4, 4, 6, 6, 6, 2, 2, 2, 5]


# How does slicing works in array
# arr[start : stop : step]

In [16]:
arr5 = [1,2,3,4,5,6,7,8,9]
print(arr5[0:5:2])

[1, 3, 5]


In [1]:
dic4 = {"a":1, "b": 2, "c":3}

# How to use double ended queue in python using collections module

In [8]:
from collections import deque

li8 = deque([1,5,7])
print(li8)

deque([1, 5, 7])


In [9]:
li8.appendleft(9)
print(li8)

deque([9, 1, 5, 7])


In [10]:
li8.append(10)
print(li8)

deque([9, 1, 5, 7, 10])


In [11]:
li8.pop()
print(li8)

deque([9, 1, 5, 7])


In [12]:
li8.popleft()
print(li8)

deque([1, 5, 7])


In [13]:
print(1)

1


# How to check if a number is power of 2 using bitwise "&" operator

In [14]:
print(bin(8))

0b1000


In [15]:
print(bin(7))

0b111


In [16]:
print(bin(16))

0b10000


In [17]:
print(bin(15))

0b1111


### if a number is power of 2 it has only one bit ,set as 1 

In [18]:
def power_of_two(n):
    if n <= 0:
        return False
    else:
        return bin(n).count("1") == 1

In [19]:
print(power_of_two(16))

True


In [20]:
print(power_of_two(17))

False


In [22]:
for i in range(5, 0, -1):
    print(i)

5
4
3
2
1


In [23]:
dp = [1] * 5
print(dp)

[1, 1, 1, 1, 1]


In [25]:
arr6 = [i for i in range(1, 9)]

In [26]:
print(arr6)

[1, 2, 3, 4, 5, 6, 7, 8]


In [27]:
print(sum(arr6[0:6]))

21


In [29]:
print(sum(arr6[5:]))

21


In [30]:
def fib2(n2):
    # bottom up with Tabulation
    #self.count2 += 1
    if n2 <= 1:
        return n2       
    else:
        li = [0, 1]
        for i in range(2,n2+1):
            value = li[i-1] + li[i-2]
            li.append(value)
        return li[n2]

In [31]:
print(fib2(10))

55


# fibonacci series using top down with memorization approach

In [24]:
def fib(n):
    # top down with memorization and recursion
    #self.count += 1
    cache = {}
    if n in cache:
        return cache[n]
    if n <= 1:
        result = n
    else:
        result = fib(n-1) + fib(n-2)
    cache[n] = result
    return result

# fibonacci series using only recursion

In [25]:
def fib1(n1):
    # using only recursion
    #self.count1 +=1
    if n1 <= 1:
        return n1
    else:
        return fib1(n1-1) + fib1(n1-2)

# fibonacci series using bottom up approach with tabulation 

In [26]:
def fib2(n2):
    #bottom up with Tabulation
    #self.count2 += 1
    if n2 <= 1:
        return n2       
    else:
        li = [0, 1]
        for i in range(2,n2+1):
            value = li[i-1] + li[i-2]
            li.append(value)
        return li[n2]

# time complexity in increasing order


O(1) - constant time \
O(log n) - logarithmic time \
O(n) - linear time \
O(n log n) - log-linear time \
O(n^2) - quadratic time \
O(n^3) - cubic time \
O(2^n) - exponential time 


In [27]:
from time import time
num = 30

start_time = time()
print(fib(num))
end_time = time()
print(end_time - start_time)

start_time = time()
print(fib1(num))
end_time = time()
print(end_time - start_time)

start_time = time()
print(fib2(num))
end_time = time()
print(end_time - start_time)

832040
1.7771306037902832
832040
0.8508892059326172
832040
0.00014972686767578125


In [37]:
print(int("101", 2))

5


In [2]:
print(int("11",2))

3


In [1]:
li = [1, 2, 4, 6, 4, 6]
print(li.index(4))

2


In [17]:
from collections import deque

queue1 = deque()

queue1.append(1)
queue1.append(2)
queue1.appendleft(3)
queue1.appendleft(4)

In [18]:
print(queue1)
x = queue1.pop()
y = queue1.popleft()
print(queue1)
print(x)
print(y)

deque([4, 3, 1, 2])
deque([3, 1])
2
4


# in-built iter and next function used to in generator

In [14]:
list6 = [1,2,3,4,5]
iter1 = iter(list6)

while iter1:
    try:
        print(next(iter1))
    except StopIteration:
        break

1
2
3
4
5


In [1]:
my_string = "hello, world!"
hash_value = hash(my_string)
print(hash_value)


4433115548730418304


# print matrix values in row wise and column wise

In [6]:
from numpy import array
mat1 = array([[1,2,3,4],[5,6,7,8], [2,3,4,5], [6,7,8,9]])

m = len(mat1)
n = len(mat1[0])

print(mat1)

for i in range(m):
    for j in range(n):
        print(mat1[i][j], end= " ")

print()
for j in range(n):
    for i in range(m):
        print(mat1[i][j], end=" ")


[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]
 [6 7 8 9]]
1 2 3 4 5 6 7 8 2 3 4 5 6 7 8 9 
1 5 2 6 2 6 3 7 3 7 4 8 4 8 5 9 

In [7]:
list7 = [1]
list8 = [2]
list9 = list7 + list8
print(list9)

[1, 2]


# recursion function

In [12]:
def rec1(num):
    if num == 10:
        return 

    rec(num-1)
    print(num)

In [13]:
def rec2(num):
    if num == 10:
        return 
    print(num)
    rec(num-1)


In [14]:
rec2(15)

15
11
12
13
14


In [15]:
rec1(15)

11
12
13
14
15


# function call with stack overflow exception and maximum recursion exception

In [ ]:
try:
    rec(9999)
except OverflowError:
    print("overflow")
except RecursionError:
    print("maximum recurison")

In [ ]:
try:
    rec(9999)
except (OverflowError, RecursionError):
    print("exception error")

### add two numbers

In [7]:
from collections import deque
class Solution():
    def list_sum(self, l1, l2):
        ans = deque([])
        forward = 0
        rang = len(l1)
        for i in range(rang -1, -1, -1):
            sum_num = l1[i] + l2[i] + forward
            if sum_num // 10 == 0:
                ans.appendleft(sum_num)
            else:
                ans.appendleft(sum_num % 10)
                forward = sum_num // 10
        return ans
l1 = [2,4,9]
l2 = [5,6,4]

print(Solution().list_sum(l1, l2))

deque([8, 1, 3])


# covert string to array

In [8]:
s = "PAYPALISHIRING"

In [9]:
print(s)

PAYPALISHIRING


In [10]:
s = list(s)

In [11]:
print(s)

['P', 'A', 'Y', 'P', 'A', 'L', 'I', 'S', 'H', 'I', 'R', 'I', 'N', 'G']


### reverse a string

In [12]:
str1 = "a1b2c3"
str2 = str1[::-1]
print(f"{str1}, {str2}")

a1b2c3, 3c2b1a


### reverse a number

In [14]:
num1 = 1234
num = 0
while num1 != 0:
    tail = num1 % 10
    num = num * 10 + tail
    num1 = num1 // 10

print(num1, num)

0 4321
