In [1]:
import torch
import torchvision

create a tensor

In [13]:
tensor1 = torch.tensor([1,2,3])
zero_tensor = torch.zeros(2,3)
rand_tensor = torch.rand(3,2)
print(tensor1)

tensor([1, 2, 3])


In [14]:
for x in tensor1:
    print(x)

tensor(1)
tensor(2)
tensor(3)


In [15]:
for i in range(len(zero_tensor)):
    for j in range(len(zero_tensor)):
        print(zero_tensor[i][j])

tensor(0.)
tensor(0.)
tensor(0.)
tensor(0.)


convert numpty array to tensor

In [8]:
import numpy as np

ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1)

tensor2 = torch.from_numpy(ar1)
print(tensor2)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [17]:
import torch.nn as nn

class MyNetwork(nn.Module):
    def __init__(self):
        super(MyNetwork, self).__init__()
        self.fc = nn.Linear(10, 5)
    
    def forward(self, x):
        x = self.fc(x)
        return x


In [2]:
import torch
import torch.nn as nn

# Define a custom neural network
class MyNetwork(nn.Module):
    def __init__(self):
        super(MyNetwork, self).__init__()
        
        # Define the layers of the network
        
        # Fully connected layer: input size is 10, output size is 5
        self.fc = nn.Linear(10, 5)
        
        # ReLU activation function
        self.relu = nn.ReLU()
        
        # Fully connected layer: input size is 5, output size is 2
        self.output = nn.Linear(5, 2)
    
    def forward(self, x):
        # Define the forward pass of the network
        
        # Pass the input through the first linear layer and apply the linear transformation
        x = self.fc(x)
        
        # Apply the ReLU activation function to introduce non-linearity
        x = self.relu(x)
        
        # Pass the output of the ReLU activation through the second linear layer
        # to obtain the final output of the network
        x = self.output(x)
        
        # Return the output
        return x


# Create an instance of the network
net = MyNetwork()

# Create random input data
input_data = torch.randn(1, 10)

# Perform forward pass
output = net(input_data)

# Print the output
print(output)

# Define a loss function
loss_function = nn.MSELoss()

# Define a target
target = torch.randn(1, 2)

# Compute the loss
loss = loss_function(output, target)

# Perform backpropagation and update the weights
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
optimizer.zero_grad()
loss.backward()
optimizer.step()


tensor([[0.1833, 0.4465]], grad_fn=<AddmmBackward0>)


In [2]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device
