In [9]:
sent = "My name is biswajeet and i live in rayagada"
print(sent)

My name is biswajeet and i live in rayagada


In [10]:
sent = list(sent.split(" "))
print(sent)

['My', 'name', 'is', 'biswajeet', 'and', 'i', 'live', 'in', 'rayagada']


In [12]:
dic = {}
for key,value in enumerate(sent):
    dic[key] = value
print(dic)

{0: 'My', 1: 'name', 2: 'is', 3: 'biswajeet', 4: 'and', 5: 'i', 6: 'live', 7: 'in', 8: 'rayagada'}


In [13]:
list = []
for key in dic.keys():
    list.append(key)
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [9]:
intervals = [[1,3],[2,6],[8,10],[15,18]]
intervals = sorted(intervals, key=lambda i: i[0])
print(intervals)

[[1, 3], [2, 6], [8, 10], [15, 18]]


In [6]:
from collections import deque
num = deque([1,2,4])
print(num)
num.appendleft(4)
print(num)

deque([1, 2, 4])
deque([4, 1, 2, 4])


In [2]:
nums= [1,2,3,5]
print(nums[-1])

5


In [1]:
7//2

3

In [4]:
num = [1,2,4]
#num.reverse()
print(num)
num1 = num[::-1]
print(num1)

[1, 2, 4]
[4, 2, 1]


In [8]:
li = [1,2]
li2 = [3,4]
print(li + li2)

[1, 2, 3, 4]


In [1]:
9/8

1.125

In [1]:
def fd(count):
    return count+1

In [2]:
coun = 1
print(fd(coun))

2


In [1]:
nums = [1,2,3]
print(nums)
print(nums[::-1])

[1, 2, 3]
[3, 2, 1]


In [1]:
print("hello")

hello


In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl 
import tensorflow as ts

2023-03-22 12:37:02.990907: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-22 12:37:05.660229: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-22 12:37:05.660407: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-22 12:37:12.335796: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [26]:
from collections import defaultdict, Counter

dic = defaultdict(set)
print(dic[0].add("a"))
dic[0].add("b")

None


In [27]:
dic

defaultdict(set, {0: {'a', 'b'}})

In [12]:
dic[0] = "a"
print(dic)

defaultdict(<class 'set'>, {0: 'a'})


In [13]:
print(dic[1])

set()


In [18]:
dic1 = defaultdict(str)

In [19]:
dic1[0] = "a"

In [20]:
dic1

defaultdict(str, {0: 'a'})

In [1]:
grid = [[0,1,1],[1,0,1],[0,0,1]]

In [10]:
for i in range(len(grid)):
    for j in range(len(grid[i])):
        print(grid[j][i])







        #onesCol = len([x for x in grid[i] if x == 1])
        #zerosCol = len([x for x in grid[i] if x == 0])
        #print(onesCol)
        #print(zerosCol)

0
1
0
1
0
0
1
1
1


In [7]:
for i in range(len(grid)):
        print(grid[i])
        onesRow = len([x for x in grid[i] if x == 1])
        zerosRow = len([x for x in grid[i] if x == 0])
        print(onesRow)
        print(zerosRow)

[0, 1, 1]
2
1
[1, 0, 1]
2
1
[0, 0, 1]
1
2


# create a empty without using numpy

In [17]:
mat1 = np.zeros((3,3))

In [18]:
print(mat1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
mat2 = np.zeros(((2,2,3)))

In [22]:
print(mat2)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
m = 3
n = 4

mat3 = [[] for i in range(m)]
print(mat3)
for i in range(m):
    mat3[i] = [0] * n
print(mat3)

[[], [], []]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [26]:
print(np.ones((3,3), dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# cartesian product using itertools

In [27]:
A = [2,3,5]
B = [4,6,2]
C = [8,3,6]

In [28]:
from itertools import product

pro = list(product(A, B, C))

In [29]:
print(pro)

[(2, 4, 8), (2, 4, 3), (2, 4, 6), (2, 6, 8), (2, 6, 3), (2, 6, 6), (2, 2, 8), (2, 2, 3), (2, 2, 6), (3, 4, 8), (3, 4, 3), (3, 4, 6), (3, 6, 8), (3, 6, 3), (3, 6, 6), (3, 2, 8), (3, 2, 3), (3, 2, 6), (5, 4, 8), (5, 4, 3), (5, 4, 6), (5, 6, 8), (5, 6, 3), (5, 6, 6), (5, 2, 8), (5, 2, 3), (5, 2, 6)]


In [2]:
list1 = [1, 2]
print(min(list1))

1


In [1]:
num = float("inf")

In [2]:
print(num)

inf


In [4]:
print(22 // 10)

2


In [2]:
print(5 // 10)

0


In [3]:
print(12 % 10)

2


In [5]:
print(13234 % 10)

4


In [1]:
my_name = input('What is your name? ')  # default message
print('Hi, {}'.format(my_name))
# What is your name? Martha
# Hi, Martha

Hi, biswa


In [2]:
response_code = 201

match response_code:
    case 200:
        print("OK")
    case 201:
        print("Created")
    case 300:
        print("Multiple Choices")
    case 307:
        print("Temporary Redirect")
    case 404:
        print("404 Not Found")
    case 500:
        print("Internal Server Error")
    case 502:
        print("502 Bad Gateway")
    case _:
        print("Response code not recognized")


Created


In [3]:
today = "Tuesday"

match today:
    case "Friday":
        print("its not")
    case "sunday":
        print("its not")
    case "Tuesday":
        print("match found")

match found


In [5]:
li2 = [1,2,34]
len(li2)

3

In [8]:
furniture = ['table', 'chair', 'rack', 'shelf']

for index, item in enumerate(furniture, start=1):
    print(f'index: {index} - item: {item}')

index: 1 - item: table
index: 2 - item: chair
index: 3 - item: rack
index: 4 - item: shelf
